import { beforeEach, describe, expect, it, vi } from 'vitest';
import { NextRequest } from 'next/server';
import { GET as getUser } from './route';
import { GET as listUploads, POST as upload } from './upload/route';

// Proxies onto Django's core app: HealthView at /user/ and UploadView at
// /user/upload.

const BACKEND = 'http://10.200.14.39:8999';
const mockFetch = vi.fn();

const request = (url: string, init: RequestInit = {}) =>
  new NextRequest(`http://localhost:3000${url}`, init as ConstructorParameters<typeof NextRequest>[1]);

beforeEach(() => {
  vi.stubGlobal('fetch', mockFetch);
  mockFetch.mockReset();
});

describe('GET /user/', () => {
  it('relays the identity the backend reports', async () => {
    mockFetch.mockResolvedValue(
      new Response(JSON.stringify({ netid: 'ab123', username: 'Ada Lovelace', role: 'student' }), {
        status: 200,
        headers: { 'Content-Type': 'application/json' },
      }),
    );

    const response = await getUser(request('/user/', { headers: { UID: 'ab123' } }));

    expect(mockFetch.mock.calls[0][0]).toBe(`${BACKEND}/user/`);
    await expect(response.json()).resolves.toEqual({
      netid: 'ab123',
      username: 'Ada Lovelace',
      role: 'student',
    });
  });

  it('relays 401 for an unauthenticated caller', async () => {
    mockFetch.mockResolvedValue(
      new Response(JSON.stringify({ message: 'Unauthorized' }), { status: 401 }),
    );

    const response = await getUser(request('/user/'));

    expect(response.status).toBe(401);
  });

  it('reports an unreachable backend as 502', async () => {
    mockFetch.mockRejectedValue(new Error('ECONNREFUSED'));

    expect((await getUser(request('/user/'))).status).toBe(502);
  });
});

describe('/user/upload', () => {
  it('lists the caller documents', async () => {
    mockFetch.mockResolvedValue(
      new Response(JSON.stringify({ netid: 'ab123', document: ['handbook.pdf'] }), {
        status: 200,
        headers: { 'Content-Type': 'application/json' },
      }),
    );

    const response = await listUploads(request('/user/upload'));

    expect(mockFetch.mock.calls[0][0]).toBe(`${BACKEND}/user/upload`);
    await expect(response.json()).resolves.toEqual({ netid: 'ab123', document: ['handbook.pdf'] });
  });

  it('passes the multipart body through with the file_ field intact', async () => {
    mockFetch.mockResolvedValue(
      new Response(JSON.stringify({ message: 'File uploaded successfully' }), { status: 201 }),
    );

    const form = new FormData();
    form.append('file_', new File(['%PDF-1.4'], 'syllabus.pdf', { type: 'application/pdf' }));

    const response = await upload(
      request('/user/upload', { method: 'POST', body: form, headers: { UID: 'ab123' } }),
    );

    expect(response.status).toBe(201);

    const [url, init] = mockFetch.mock.calls[0];
    expect(url).toBe(`${BACKEND}/user/upload`);
    expect(init.body).toBeInstanceOf(FormData);
    expect((init.body as FormData).get('file_')).toBeInstanceOf(File);
    // The boundary must be generated by fetch, not copied from the inbound request.
    expect((init.headers as Headers).get('content-type')).toBeNull();
  });

  it('relays a backend rejection of the upload', async () => {
    mockFetch.mockResolvedValue(
      new Response(JSON.stringify({ file_: ['File should end with PDF'] }), { status: 400 }),
    );

    const form = new FormData();
    form.append('file_', new File(['nope'], 'notes.txt', { type: 'text/plain' }));

    const response = await upload(request('/user/upload', { method: 'POST', body: form }));

    expect(response.status).toBe(400);
  });
});
